### ISSUE TITLE
Provide Auto-complete config sample?

### ISSUE THREAD

**Issue by mikestecker** [newism/craft3-fields#1]
Could you provide an auto-complete configuration example? I've tried putting in some parameters in a few different ways but it keeps complaining it's not proper JSON.

I've tried it this way:
```
types: ['(cities)'],
componentRestrictions: {country: "us"}
```
and also this way:
```
{
types: ['(cities)'],
componentRestrictions: {country: "us"}
}
```
but still no dice. It keeps telling me `The JSON string supplied is not valid: Syntax error</code>`

**Comment by leevigraham** [comment]
Valid JSON requires keys and values to be quoted with double quotes:

```json
{
    "types": ["cities"],
    "componentRestrictions": {
        "country": "us"
    }
}
```
