### ISSUE TITLE
Templating Shortcodes

### ISSUE THREAD

**Issue by aliwilson** [newism/craft3-fields#11]
Would you mind pointing me in the right direction as to how to output the fields within a template? I've tried a tested a few different options but can't work it out!

Many Thanks

**Comment by aliwilson** [comment]
Funny the minute i asked for help i found out how to do it, for anyone else who needs it - here are some working examples with the field handle set as 'address':

{{entry.address.addressLine2}} - Address 1
{{entry.address.addressLine2}} - Address 2
{{entry.address.latitude}} - Longitude
{{entry.address.latitude}} - Latitude
{{entry.address.mapUrl}} - Map URL

any others you need can be found by inspecting the field in developer tools, check the class name '...fieldRow - xxxx'

**Comment by leevigraham** [comment]
Yep  have to add some front end documentation :)

**Comment by leevigraham** [comment]
The [`normalizeValue`](https://github.com/newism/craft3-fields/blob/master/src/fields/Address.php#L504) method always returns an [`AddressModel`](https://github.com/newism/craft3-fields/blob/master/src/models/AddressModel.php). All public properties are available:

```
{{ entry.address.countryCode }}
{{ entry.address.administrativeArea }}
{{ entry.address.locality }}
{{ entry.address.dependentLocality }}
{{ entry.address.postalCode }}
{{ entry.address.sortingCode }}
{{ entry.address.addressLine1 }}
{{ entry.address.addressLine2 }}
{{ entry.address.organization }}
{{ entry.address.recipient }}
{{ entry.address.locale }}
{{ entry.address.placeData }}
{{ entry.address.latitude }}
{{ entry.address.longitude }}
{{ entry.address.mapUrl }}
```

**Comment by leevigraham** [comment]
Added in 8909c91b7d93eb57c2a0f333c1445c7550278601
