### ISSUE TITLE
Split out phone number into parts

### ISSUE THREAD

**Issue by mikestecker** [newism/craft3-fields#12]
Can you add the ability to format the phone number in a more presentable way? Something like `(555) 555-1234` or `555-555-1234` or even possibly the give the flexibility to format it any way we want by outputting the different sections of the number: `areacode`, `prefix`, `linenumber` etc?

**Comment by leevigraham** [comment]
@mikestecker,

You should be able to use the following in your template:

```
{{ some_field.format('E164') }}
{{ some_field.format('international') }}
{{ some_field.format('national }}
{{ some_field.format('RFC3966') }}```

Which will provide different standard formats.

There's also

```{{ some_field.rawInput }}```

Which should be exactly as the phone number was typed.

I don't think there is a way to pull out areacode, prefix or line number.

Here's a demo of the lib: https://giggsey.com/libphonenumber/

**Comment by mikestecker** [comment]
Nice! `.format('national')` is exactly what I was looking for. I was asking about the full breakdown because sometimes designers will want to display stuff as a `555.555.1234` pattern or whatnot which I know isn't considered "standard". Anyway, thanks for the tips, do you mind updating the readme with this info?

**Comment by leevigraham** [comment]
@mikestecker Yep I'll update the readme. 

>  I was asking about the full breakdown because sometimes designers will want to display stuff as a 555.555.1234 pattern or whatnot which I know isn't considered "standard".

I understand the need for this but I don't think it's possible given the fact there are so man countries. The underlying library doesn't seem to support it.

Related: https://github.com/googlei18n/libphonenumber/issues/46

**Comment by leevigraham** [comment]
@mikestecker, One way you might be able to achieve this is to use the national formatting + some twig regexp magic. https://github.com/low/low_regex/
