### ISSUE TITLE
Cannot read property 'serialize' of undefined - Address.js:88

### ISSUE THREAD

**Issue by bphippen** [newism/craft3-fields#15]
Hi there, love the plugin but getting an error on line 88 of Address.js

Cannot read property 'serialize' of undefined

Worked great on Craft 3 beta but not working on Craft 3 RC

Also the default country is not populating.

**Comment by leevigraham** [comment]
@bphippen Which version are you using?

**Comment by bphippen** [comment]
@leevigraham 3.0.0-RC1

It seems to work fine after the address autofill fails once, then you save the entry, then try the address again.

**Comment by leevigraham** [comment]
Ok found the issue… Craft has updated some of it's HTML, I'll sort a fix now.
