### ISSUE TITLE
Telephone field causes a PHP error when entry is saved

### ISSUE THREAD

**Issue by romainpoirier** [newism/craft3-fields#18]
```
PHP Fatal Error – yii\base\ErrorException
Method newism\fields\models\TelephoneModel::__toString() must not throw an exception, caught TypeError: Argument 1 passed to libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, null given, called in /vendor/newism/craft3-fields/src/models/TelephoneModel.php on line 66
```

This happens whatever the phone prefix or phone number, even if empty.

Craft CMS version : 3.0.0-RC7.1

**Comment by mikestecker** [comment]
Came to report the same issue:

`Method newism\fields\models\TelephoneModel::__toString() must not throw an exception, caught TypeError: Argument 1 passed to libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, null given`

**Comment by mikestecker** [comment]
After updating to RC8 today the issue still exists

**Comment by mikestecker** [comment]
@leevigraham Happy Birthday! Hope you have a great one!

**Comment by romainpoirier** [comment]
@leevigraham Happy Birthday 🎂 ! Thank you!

**Comment by E2design** [comment]
Same issue here on 3.0.0-RC8

`Method newism\fields\models\TelephoneModel::__toString() must not throw an exception, caught TypeError: Argument 1 passed to libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, null given, called in /storage/av04180/www/thetag_html/vendor/newism/craft3-fields/src/models/TelephoneModel.php on line 66`

**Comment by leevigraham** [comment]
v 0.0.8 should fix the issue.
