### ISSUE TITLE
Field setting "Translation method" set to "Not translatable" don't work

### ISSUE THREAD

**Issue by E2design** [newism/craft3-fields#20]
Setting the Field setting "Translation method" to "Not translatable" in a multi-language (2 sites) set-up still gives the option to reenter translate the date in the other language. While forcing this however, the complete values from the first language disappear and are not recoverable.

![schermafdruk 2018-02-09 15 30 37](https://user-images.githubusercontent.com/5907530/36032606-d9facaa6-0dae-11e8-973c-a02f1f6938ce.png)

**Comment by leevigraham** [comment]
@E2design Thanks for the report. I haven't considered any multi-language functionality as of yet. I'll add it to the roadmap.

**Comment by E2design** [comment]
In the light of the Craft3 "sites" function of which multi-language is part of this is more a necessity then an enhancement 👍

**Comment by leevigraham** [comment]
@E2design do you have a demo project I can take a look at?

**Comment by leevigraham** [comment]
I've re-read your initial comment and I don't think this is an issue. You've set the field to "Not translatable" so in my understanding saving either site will overwrite the other site. Changing the translation method to Translate for each site also works as expected
