### ISSUE TITLE
Remove roave/security-advisories requirement?

### ISSUE THREAD

**Issue by mikestecker** [newism/craft3-fields#21]
Having some issues updating composer in regards to `roave/security-advisories`. I'm on C3 RC10.1 and this morning, when running `composer update`, I get the following error:

```
  Problem 1
    - Conclusion: remove craftcms/cms 3.0.0-RC10.1
    - Conclusion: don't install craftcms/cms 3.0.0-RC10.1
    - Installation request for craftcms/cms ^3.0.0-RC10 -> satisfiable by craftcms/cms[3.0.0-RC10, 3.0.0-RC10.1].
    - Conclusion: remove roave/security-advisories dev-master
    - craftcms/cms 3.0.0-RC10 requires yiisoft/yii2 ~2.0.13.0 -> satisfiable by yiisoft/yii2[2.0.13.1, 2.0.13].
    - yiisoft/yii2 2.0.13 conflicts with roave/security-advisories[dev-master].
    - yiisoft/yii2 2.0.13.1 conflicts with roave/security-advisories[dev-master].
    - roave/security-advisories dev-master conflicts with yiisoft/yii2[2.0.13.1].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
```

Also, when I was scrolling the Craft 3 Slack group this morning, I saw @brandonkelly say "you can remove the `roave/security-advisories` requirement from your composer.json file for now. Yii 2.0.14 was just released this morning; we will get it into tomorrow's RC11 update"

But when I removed it and re-ran `composer update`, I still get a similar error which pointed me to `craft3-fields` having the requirement still there:

```
  Problem 1
    - newism/craft3-fields 0.0.8 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - newism/craft3-fields 0.0.8 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Removal request for roave/security-advisories == 9999999-dev
    - Installation request for newism/craft3-fields ^0.0.8 -> satisfiable by newism/craft3-fields[0.0.8].
```

Can you update your `composer.json` file to resolve it?

**Comment by brandonkelly** [comment]
Yeah that package should only ever be required by a _project’s_ composer.json; not a dependency’s.

**Comment by leevigraham** [comment]
Will fix. :)

**Comment by leevigraham** [comment]
Removed in 01ece12431fe9578cd7c0c634b6cc4acccf8a6c6. v0.0.9 tagged :)
