### ISSUE TITLE
Accessing full country name?

### ISSUE THREAD

**Issue by andrewmenich** [newism/craft3-fields#28]
Is it possible to access the whole country name instead of just the two-digit code? It appears to be a method on the commerceguys/addressing library but is not available in this plugin?

**Comment by leevigraham** [comment]
Hmmm… doesn't look like it unless you go through `myfield.placedata`. Should be easy to add tho.

**Comment by adrienne** [comment]
i also need this, @leevigraham, because for manually set addresses there's no placedata.

**Comment by leevigraham** [comment]
@adrienne / @adrienne 

Checkout: https://github.com/newism/craft3-fields/releases/tag/0.0.11

I've added:

```
{{ entry.address.country.countryCode }}
{{ entry.address.country.name }}
{{ entry.address.country.threeLetterCode }}
{{ entry.address.country.numericCode }}
{{ entry.address.country.currencyCode }}
{{ entry.address.country.locale }}
```
