### ISSUE TITLE
Default Country Code doesn't do anything.

### ISSUE THREAD

**Issue by webrgp** [newism/craft3-fields#30]
I've set the default country on the address field, but when I create a new entry, the default country isn't selected.

Digging into the code, on fields/Address.php, from line 229, should be changed to:

```php
$countryCode = $value ? $value->getCountryCode() : $this->defaultCountryCode;
$countryCodeField = Craft::$app->getView()->renderTemplate(
    'nsm-fields/_components/fieldtypes/Address/input/countryCode',
    [
        'name' => $this->handle,
        'value' => $countryCode,
        'field' => $this,
        'id' => $id,
        'namespacedId' => $namespacedId,
        'settings' => $fieldSettings,
        'countryOptions' => $this->getCountryOptions(),
    ]
);
```

and on templates/_components/fieldtypes/Address/input/countryCode.twig, change to:

```twig
{% import "_includes/forms" as forms %}
<div class="field-countryCode">
    <label for="{{ name ~ '-countryCode' }}">{{ 'Country' | t('app') }}</label>
    {{ forms.select({
        id: name ~ '-countryCode',
        name: name ~ '[countryCode]',
        value: value,
        options: countryOptions
    }) }}
</div>
```

**Comment by webrgp** [comment]
One quick note: after I've put the Google API key, I am still getting errors :-/

**Comment by adrienne** [comment]
I'm having the same problem.

**Comment by leevigraham** [comment]
@webrgp @adrienne I'm not sure what I was thinking with default country code. I think I might have copied that from the telephone input.

How would you expect a default country code to work? Would it render all the fields below? Are you planning to hide the auto complete?

**Comment by leevigraham** [comment]
Figured it out. https://github.com/newism/craft3-fields/releases/tag/0.0.14 should fix this issue.
