### ISSUE TITLE
Autocomplete on US addresses frequently puts the address in the wrong line

### ISSUE THREAD

**Issue by adrienne** [newism/craft3-fields#32]
I'm noticing that on address autocomplete of US addresses, what should be address line 1 frequently gets put into address line 2 if there is no line 2 in the returned data. This should definitely not happen1

**Comment by leevigraham** [comment]
@adrienne Can you provide an example address?

**Comment by adrienne** [comment]
@leevigraham - Yeah, try entering "Whitman College" and selecting the one in Walla Walla, Washington, US. You'll see that it populates the address but it puts what should be Line 1 into Line 2

**Comment by leevigraham** [comment]
This is the expected behaviour. Line 1 is reserved for things like apartment number. Google Geo-coding only returns the street address not individual apartments.

**Comment by adrienne** [comment]
@leevigraham - This is the wrong behavior for US addresses. The street address, in the US, should always be line 1; apartment or suite number should be in line 2.

**Comment by leevigraham** [comment]
Hmm… Interesting.

There's two use cases for addresses… postal addresses and locations. Google doesn't return "Street Address Line 1" and "Street Address Line 2" in it's geocoding… only a street address.

I think I'm going to merge address line 1 and address line 2 into a single input. Does the post office care if apartment and street are on the same line?

Eg: Apt 1, Some Street Name

**Comment by adrienne** [comment]
@leevigraham - sorry, i had missed this. The post office does care, yes - it can all be on the same line, but the street address _must always come first_. So:

123 Some Street Name, Apt 1

would be okay, but

Apt 1, 123 Some Street Name

would _not_.

**Comment by CRHain88** [comment]
Google Places API refers to the apartment/suite as `subpremise`.

Also, as @adrienne mentioned, It's confusing in the US and my editors are copy/pasting the data from the second line into the first line.
