### ISSUE TITLE
Depreciation error maybe related to missing PHP extensions

### ISSUE THREAD

**Issue by stovepot** [newism/craft3-fields#33]
This error perseveres: `Fields’ isEmpty() method has been deprecated. Use isValueEmpty() instead.` 

Looks like it is related to the phone number field...

Running on:

PHP: 7.1.19 (MAMP Pro 5+)
MySQL 5.7.21
Craft Solo 3.0.20
NSM Fields | 0.0.10
All System Report's Requirements good (including the Intl extension).

**Comment by leevigraham** [comment]
Hi @stovepot, I believe this is fixed in master: https://github.com/newism/craft3-fields/pull/31. I just need to prep a release.

**Comment by leevigraham** [comment]
@stovepot Checkout: https://github.com/newism/craft3-fields/releases/tag/0.0.11
