### ISSUE TITLE
address field : latitude & longitude not being saved

### ISSUE THREAD

**Issue by nicolasbinet** [newism/craft3-fields#35]
After searching an address and saving it in an entry, longitude and latitude are not saved, even though they are present in the placeData, and mapUrl is correctly saved.
Is there anything special ?

**Comment by leevigraham** [comment]
Can you let me know the address you were trying and the version of Craft?

**Comment by nicolasbinet** [comment]
The problem occurs for multiple addresses, which are all reported on this page : 
https://www.dolphin-charger.com/network

We're using Craft 3.0.28 & NSM Fields 0.0.11.

**Comment by leevigraham** [comment]
Okie dokie… that's a lot of addresses. I should be able to check it out tonight.

**Comment by leevigraham** [comment]
@nicolasbinet Do you have "Show Latitude / Longitude" enabled in the field settings?

![2018-11-01 15 49 48](https://user-images.githubusercontent.com/25124/47833345-5e5e6680-ddee-11e8-92a2-ad494b1073a9.gif)

![2018-11-01 15 48 57](https://user-images.githubusercontent.com/25124/47833348-64ecde00-ddee-11e8-9963-90104a7c7b83.gif)

**Comment by leevigraham** [comment]
no field means it's not part of the submission… pretty easy change tho… I can change the field type to hidden.

**Comment by nicolasbinet** [comment]
for me, that would be a great idea.
being able to evolve a field, without re-saving all addresses.
