### ISSUE TITLE
Suggestion: Unbundle into separate field repos

### ISSUE THREAD

**Issue by joshuabaker** [newism/craft3-fields#36]
Separate repos would allow installing only the fields required as well as allowing field-specific issues.

This repo could still exist as a way to batch install (i.e. using composer).

Thoughts on this?

**Comment by leevigraham** [comment]
It's on the roadmap! :) 

![image](https://user-images.githubusercontent.com/25124/47832818-b3e54400-ddeb-11e8-8c4e-10fb522627c2.png)
