### ISSUE TITLE
Adresse cannot contain emoji

### ISSUE THREAD

**Issue by nicolasbinet** [newism/craft3-fields#39]
After searching for the address below, get a result and saving, we get an error "**field** cannot contain emoji."
`
CAP 190   
7 avenue du Dr Pierre Nicolas   
29900 CONCARNEAU`

Can the validation be more flexible to allow content submitted to and delivered by Google.

**Comment by leevigraham** [comment]
Does that address contain emoji?

**Comment by nicolasbinet** [comment]
being more precise on the process : 
- I searched for "Accastillage Diffusion Concarneau"  (screenshot tbelow)
- Validate the first and only result
- Save the entry without any other edit
- Voila, get the error !

<img width="1003" alt="capt_field_address" src="https://user-images.githubusercontent.com/867710/49543114-9f5b0680-f8d7-11e8-8dc8-5707f448ed57.png">

**Comment by leevigraham** [comment]
Relevant emoji:

![image](https://user-images.githubusercontent.com/25124/51161140-4bcfd580-18e5-11e9-9d3e-b9fd867adef8.png)

Also related: https://github.com/craftcms/cms/issues/1627

**Comment by leevigraham** [comment]
@nicolasbinet I'm pretty sure this is fixed in v0.0.12.

I'm now serialising the address manually using json_encode and replacing emoji with Crafts `StringHelper::encodeMb4`
