### ISSUE TITLE
"Request missing required body param" after selecting address suggestion

### ISSUE THREAD

**Issue by malamoet** [newism/craft3-fields#42]
Hi, i'm having troubles with the address field.

After selecting an address suggestion from the dropdown nothing happens (the address part fields aren't showing).

![schermafbeelding 2018-12-02 om 12 21 12](https://user-images.githubusercontent.com/23460374/49339122-55e78e80-f62d-11e8-8a58-43916382f043.png)

The request that happens on selecting a location is throwing a 400 error:

![schermafbeelding 2018-12-02 om 12 24 03](https://user-images.githubusercontent.com/23460374/49339118-4b2cf980-f62d-11e8-8d9d-c2805c60043c.png)

![schermafbeelding 2018-12-02 om 12 22 10](https://user-images.githubusercontent.com/23460374/49339100-f38e8e00-f62c-11e8-8e82-2e9f1a8929a4.png)

Any idea what i'm doing wrong or what's going on?

Thx in advance

**Comment by leevigraham** [comment]
Hmm that's a weird one… which version of Craft are you using?

**Comment by leevigraham** [comment]
@malamoet Thanks for nailing down the issue. I'll take a look… I'm pretty snowed under with work leading up to the holidays so it might be a toward the end of the week. Should be an easy fix.

**Comment by leevigraham** [comment]
@malamoet I took a look at this and it's going to be a bit more complicated than I thought. I cheated a bit and used some balck magic to change the field when the country changes. I'll look at another option.

**Comment by leevigraham** [comment]
Fixed by #59
