### ISSUE TITLE
Disabling AutoComplete breaks things!

### ISSUE THREAD

**Issue by rjhewitt3** [newism/craft3-fields#43]
This is particularly related to the Address field type. I'm not leveraging the Google API autofill, and this is a result stemming, seemingly from that. In the field configuration, I only have "Show Map Url"
and "Show Latitude / Longitude" checked. In other words, "Show Auto Complete" is disabled.

When going to my entry, I'm getting some console errors. These are breaking other fields, particularly, in my case, a "matrix" field. It's causing the buttons to add a block to no longer work.

[You can see a screenshot of the errors here →](http://steadfa.st/b955a88c0e40)

**If I enable "Show Auto Complete" the errors go away and the matrix fields starts working again. In this case, I don't want the autocomplete option.**

**Comment by leevigraham** [comment]
Looks like I need to come back and bulletproof the javascript.

**Comment by leevigraham** [comment]
Should be fixed by: https://github.com/newism/craft3-fields/pull/54
