### ISSUE TITLE
Autocomplete doesn't populate all fields

### ISSUE THREAD

**Issue by XianHain** [newism/craft3-fields#46]
The Autocomplete box does not populate the `name` or `subpremise` (apt/suite/etc) values

## Expected Behavior
When using autocomplete to find a location (example, "Mailchimp Atlanta United States"), the value "Mailchimp" would be populated in the company field, "675 Ponce De Leon Ave NE" would populate in the first Address field, and "Suite 5000" would populate in the second Address field.

## Actual Behavior
When using autocomplete to find a location (example, "Mailchimp Atlanta United States"), the value "675 Ponce De Leon Ave NE" populates in the second Address field, and the Company field and first Address field are left empty.

## Notes
As pointed out in #32, it's confusing for US users when the street address is populated on the second line. It would be nice if there was a way for the plugin to swap fields depending on the user's locality.

**Comment by leevigraham** [comment]
Thanks for raising the issue… Do you know when premise and subpremise were added to the response?

How would you expect these to be added to the address… maybe in Address Line 1. 

I'm mapping two different datasets / formats Google Geocode to the [CommerceGuys addressing model](https://github.com/commerceguys/addressing#data-model)

Hows this for a plan… If there's a premise, subpremise or floor in the Google data I'll add that to Line 1 and the street number and name to Line 2… if those values don't exist I'll add the street number and name to Line 1.

**Comment by leevigraham** [comment]
@CRHain88 According to https://github.com/newism/craft3-fields/issues/32#issuecomment-414557769 the street address must always be before the premise, subpremise?

**Comment by leevigraham** [comment]
Reference: https://pe.usps.com/text/pub28/28c2_003.htm

**Comment by leevigraham** [comment]
Reference Australian Addressing Standards: https://auspost.com.au/content/dam/auspost_corp/media/documents/Appendix-01.pdf

**Comment by leevigraham** [comment]
@CRHain88 UPS provides an alternative position for Secondary Address Unit Designators

![Screen Shot 2019-03-28 at 15 21 00](https://user-images.githubusercontent.com/25124/55129961-2aa12600-516d-11e9-8a89-bcc01b452856.png)

**Comment by CRHain88** [comment]
@leevigraham Typical convention for US Addresses is as follows:

`street_address`
`premise` `subpremise`
`locality` `administrative_area_level_1` `postal_code`
`country`

> the street address must always be before the premise, subpremise?

Whether you decide to put `street_address` above or below `premise` and `subpremise` is a matter of taste but very confusing without field labels. Many forms I've seen will say things like "Street Address", "Apt/Bldg/Ste". 

This is only a concern in the control panel, I can handle the positioning of these elements in my templates.

**Comment by adrienne** [comment]
@leevigraham - this is related to my earlier issue, btw.

**Comment by leevigraham** [comment]
@CRHain88 revisting this backlog issue… The main challenge here is the way the google autocomplete api maps to the addressing bundle which handles all the country / state / city localisation and layout.  The addressing bundle data model is different: https://github.com/commerceguys/addressing#data-model I probably need to rethink the purpose of the address field and explain it better.

**Comment by leevigraham** [comment]
Sprout Address Fieldtype for reference does the same thing: https://sprout.barrelstrengthdesign.com/docs/fields/address-field.html#templates
