### ISSUE TITLE
Name of person field becomes empty if save is done after Craft auto-saves entry

### ISSUE THREAD

**Issue by bliswebagency** [newism/craft3-fields#64]
Steps to reproduce:

1. Enter values into Name of Person field
2. Wait for the first green autosave tickmark to appear
3. Save entry
4. Name of Person field is empty

However if saving very quickly before the first autosave completes the fields values are saved correctly and not emptied.

Versions:

NSM Fields: 1.0.2
Craft Version: 3.7.11
PHP: 7.4.22

**Comment by leevigraham** [comment]
@bliswebagency I'll look into this either today or tomorrow.

**Comment by bliswebagency** [comment]
Thanks @leevigraham , let us know if you need any additional info

**Comment by leevigraham** [comment]
@bliswebagency I think I've finally figured this out. Can you try 1.0.4 if you're still using the plugin: https://github.com/newism/craft3-fields/releases/tag/1.0.4
