### ISSUE TITLE
Embed field in matrix resets everytime after hitting save.

### ISSUE THREAD

**Issue by azim1728** [newism/craft3-fields#71]
Craft CMS: 3.7.38
PHP: 7.4.28

1. Create an Entry with the NSM Embed field in matrix field.
2. Enter embed link in the field.
3. Click on 'Create Entry or Save'.
4. NSM Embed field values are reset.

Please see attached video for more idea.

https://user-images.githubusercontent.com/54146953/163718019-f0b8693c-6fdc-4b21-b352-68903328af85.mp4

**Comment by azim1728** [comment]
@leevigraham any update on this?

**Comment by azim1728** [comment]
@leevigraham hey man, hope you are doing well. Just checking if nay updates on the isssue?

**Comment by leevigraham** [comment]
@azim1728 I'm looking into this. I can see that embed fields fail to save if they're not in a matrix block… so something is going on for sure. Saving a draft sometimes works… but not always.

**Comment by leevigraham** [comment]
@azim1728 Related to: https://github.com/newism/craft3-fields/issues/62

**Comment by leevigraham** [comment]
@azim1728 Also related to: https://github.com/newism/craft3-fields/issues/64

**Comment by leevigraham** [comment]
@azim1728 Can you try updating to 1.0.4: https://github.com/newism/craft3-fields/releases/tag/1.0.4

**Comment by azim1728** [comment]
@leevigraham thanks mate I have updated the plugin. I will check if the issue still exist or not and close the issue if its fixed for me.

**Comment by azim1728** [comment]
@leevigraham it is fixed. Thanks for your efforts.
