### ISSUE TITLE
Can't install on Craft 4

### ISSUE THREAD

**Issue by robzor** [newism/craft3-fields#74]
Hi there, 

I've gone to install the plugin from the Plugin store and got this error:

```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - newism/craft3-fields 2.0.0 requires embed/embed ^4.0 -> found embed/embed[v4.0.0, ..., v4.4.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires newism/craft3-fields 2.0.0 -> satisfiable by newism/craft3-fields[2.0.0].
```

I'm running Craft 4.4.0, here are my other plugins:

```
    "craftcms/redactor": "3.0.3",
    "misterbk/mix": "1.6.0",
    "nystudio107/craft-emptycoalesce": "4.0.0",
    "nystudio107/craft-imageoptimize": "4.0.4",
    "nystudio107/craft-seomatic": "4.0.20",
    "percipioglobal/craft-colour-swatches": "4.3.0",
    "presseddigital/linkit": "4.0.4.1",
    "putyourlightson/craft-blitz": "4.4.2",
    "putyourlightson/craft-blitz-recommendations": "2.1.1",
    "putyourlightson/craft-elements-panel": "2.0.0",
    "putyourlightson/craft-sherlock": "4.3.0",
    "putyourlightson/craft-sprig": "2.5.1",
    "rynpsc/craft-phone-number": "2.1.0",
    "servd/craft-asset-storage": "3.2.11",
    "spicyweb/craft-neo": "3.7.0",
    "verbb/formie": "2.0.24",
    "verbb/super-table": "3.0.7",
    "vlucas/phpdotenv": "^5.4.0",
    "wrav/oembed": "2.3.0"
```

I'm going to assume it's the oembed plugin and yours having a bit of an issue working together?

**Comment by leevigraham** [comment]
Yep that's the exact reason: https://github.com/wrav/oembed/blob/master/composer.json#L34

Which field did you want to use out of NSM Fields?

**Comment by robzor** [comment]
Hey @leevigraham! 

I wanted to use the Address field and Telephone fields

**Comment by leevigraham** [comment]
> Maybe I could use your Embed field instead of the oEmbed plugin, it was going to be used for YouTube/Vimeo embedding primarily.

Embed field can handle that. You may need to go back and edit your content tho.

Alternatively you could fork the repo and change the dependency back to 3.0 if you know you're never going to use my embed field.

**Comment by robzor** [comment]
Thanks!
