### ISSUE TITLE
Craft 4 Autocomplete not working.

### ISSUE THREAD

**Issue by azim1728** [newism/craft3-fields#76]
**Craft CMS 4.7.0
PHP 8.2**

On inputting address field autocomplete is not working at all.

https://github.com/newism/craft3-fields/assets/54146953/5e5136d9-5a4a-491b-99e0-4e01a32f0d4d

**Comment by azim1728** [comment]
```
An Error occurred while handling another error:
TypeError: Cannot assign null to property newism\fields\models\AddressModel::$placeData of type array|string in /public_html/vendor/yiisoft/yii2/BaseYii.php:558

```

**Comment by leevigraham** [comment]
Hi @azim1728 Can you try `dev-master`:

```sh
composer update newism/craft-fields:dev-master --with-dependencies
```

I think your issue may have been fixed in: https://github.com/newism/craft3-fields/commit/6715b033e2cc2965dc25002dab839f59c6aec1f7 If so I'll create a new release.

**Comment by azim1728** [comment]
Ok let me give it a try.

**Comment by azim1728** [comment]
Hey, 
 @leevigraham  i just checked the above command it seems it is working fine.
 But I have to make changes from "newism/craft-fields:dev-master" to "newism/craft3-fields:dev-master".
 
 Please create new release.
 
 Thank you for the prompt response.

**Comment by leevigraham** [comment]
@azim1728 Done: https://github.com/newism/craft3-fields/releases/tag/2.1.0
