### ISSUE TITLE
Undefined index: countryCode

### ISSUE THREAD

**Issue by mikestecker** [newism/craft3-fields#9]
When adding a phone number field and deselecting the `Show country selector` checkbox. I am presented with an error `Undefined index: countryCode` when saving an entry.

```
in vendor/newism/craft3-fields/src/fields/Telephone.php at line 131

return new TelephoneModel($value['countryCode'], $value['rawInput']);
```

Edit: I had a look in my database to see how the field settings are stored. They give me this:
```
{"showCountrySelector":false,"defaultCountryCode":"US"}
```

**Comment by leevigraham** [comment]
@mikestecker, Thanks for the report. I'll take a look. Which version of Craft3 are you running?

**Comment by mikestecker** [comment]
@leevigraham I'm running the latest beta which is 26 I believe.

**Comment by mikestecker** [comment]
@leevigraham hey just wanted to follow up on this. I'm on beta 34 now and the problem is still happening.

**Comment by leevigraham** [comment]
@mikestecker, Whats in your entryversions table for the entry? Can you paste the value of the data column?

**Comment by mikestecker** [comment]
@leevigraham sorry for the delay... I just made it so it always show the country code dropdown at all times to get around the issue for now. Here's the relevant part of one of my entryversions tables:

`"108":{"countryCode":"US","rawInput":"765-662-9931","phoneNumber":[]}`

**Comment by leevigraham** [comment]
@mikestecker … finally getting some time to look at this. I think in more recent versions I've removed the option to hide the drop down. Which version are you currently running?

**Comment by mikestecker** [comment]
@leevigraham I'm running your latest version so that issue has gone away now. It would be nice to be able to set a default country though so the user doesn't have to select it each time.
